-- MySQL Script generated by MySQL Workbench
-- to 15. syyskuuta 2016 15.37.01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_Service_Mockup_Source
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_Service_Mockup_Source
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_Service_Mockup_Source` DEFAULT CHARACTER SET latin1 ;
USE `db_Service_Mockup_Source` ;

-- -----------------------------------------------------
-- Table `db_Service_Mockup_Source`.`code_and_user_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_Service_Mockup_Source`.`code_and_user_mapping` ;

CREATE TABLE IF NOT EXISTS `db_Service_Mockup_Source`.`code_and_user_mapping` (
  `code` LONGTEXT NOT NULL,
  `user_id` LONGTEXT NOT NULL,
  PRIMARY KEY (`code`(255)))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_Service_Mockup_Source`.`storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_Service_Mockup_Source`.`storage` ;

CREATE TABLE IF NOT EXISTS `db_Service_Mockup_Source`.`storage` (
  `surrogate_id` LONGTEXT NOT NULL,
  `json` LONGTEXT NOT NULL,
  `slr_id` LONGTEXT NOT NULL,
  PRIMARY KEY (`slr_id`(255)))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;




-- -----------------------------------------------------
-- Table `db_Service_Mockup_Source`.`ssr_storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_Service_Mockup_Source`.`ssr_storage` ;

CREATE TABLE IF NOT EXISTS `db_Service_Mockup_Source`.`ssr_storage` (
  `surrogate_id` LONGTEXT NOT NULL,
  `slr_id` LONGTEXT NOT NULL,
  `record_id` LONGTEXT NOT NULL,
  `json` LONGTEXT NOT NULL,
  `prev_record_id` LONGTEXT,
  PRIMARY KEY (`record_id`(255)))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_Service_Mockup_Source`.`surrogate_and_user_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_Service_Mockup_Source`.`surrogate_and_user_mapping` ;

CREATE TABLE IF NOT EXISTS `db_Service_Mockup_Source`.`surrogate_and_user_mapping` (
  `user_id` LONGTEXT NOT NULL,
  `surrogate_id` LONGTEXT NOT NULL,
  PRIMARY KEY (`user_id`(255)))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE USER 'MockupSource'@'%' IDENTIFIED BY 'MynorcA';
GRANT CREATE TEMPORARY TABLES, DELETE, DROP, INSERT, LOCK TABLES, SELECT, UPDATE ON db_Service_Mockup_Source.* TO 'MockupSource'@'%';
FLUSH PRIVILEGES;
