-- MySQL Script
-- 09/14/16 10:31:08

CREATE USER 'mydataaccount'@'%' IDENTIFIED BY 'wr8gabrA';
GRANT CREATE TEMPORARY TABLES, DELETE, DROP, INSERT, LOCK TABLES, SELECT, UPDATE ON MyDataAccount.* TO 'mydataaccount'@'%';
FLUSH PRIVILEGES;
